### ISSUE TITLE
Add a .error() function (same as .err())

### ISSUE THREAD

**Issue by mbrandau** [mbrandau/beautiful-logs#6]
The function should do exactly the same as `.err()`.

**Comment by azharakbar** [comment]
@mbrandau I would like to take this up .... can you clarify regarding this ?

**Comment by mbrandau** [comment]
@azharakbar The `init()` function returns an object with multiple methods (debug, info, err, etc.). I'd like that object to have another function called `error` that does exactly the same as the `err()` function. You can move the declaration of the `error()` function out of the return statement and use it in both the `err` and the `error` exports.

**Comment by azharakbar** [comment]
@mbrandau Ok .. got it ... so it required that both `err()` and `error()` both resides....even if both does the same thing .. ??

**Comment by mbrandau** [comment]
Correct. I don't want to break backward compatibility

**Comment by azharakbar** [comment]
@mbrandau Sure ... I am working on it ... :) will send PR sooon .. :)

**Comment by azharakbar** [comment]
@mbrandau I have submitted the PR .. :)

**Comment by azharakbar** [comment]
@mbrandau Hi, any changes ?

**Comment by mbrandau** [comment]
@azharakbar Please have a look at my review comments.

**Comment by azharakbar** [comment]
@mbrandau 
 ook ... i will look into it ... :)

**Comment by azharakbar** [comment]
@mbrandau I have done the changes ... pls look into the PR .. :)

**Comment by azharakbar** [comment]
@mbrandau Can i know the comments on PR ? Do you want further changes ? I have changed what all you have suggested ... :)

**Comment by mbrandau** [comment]
Didn't see your comment at first @azharakbar :smile: No more changes needed :+1:

**Comment by azharakbar** [comment]
@mbrandau Thanx man ... :)
